name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Prepare deployment
        run: |
          git config user.name "ngjinshan99"
          git config user.email "ngjinshan99@gmail.com"
          git checkout --orphan gh-pages
          git --work-tree build add --all
          git --work-tree build commit -m "Deploy"
          git push origin HEAD:gh-pages --force
          rm -r build
          git checkout -f master
          git branch -D gh-pages
